name: Manual
on:
  workflow_dispatch:
  # Actionの開始時に引数を受け取れるように設定できる。
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{  inputs.greeting }}"

